name = "nyt-mini-crossword-converter"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = false

# Environment variables
[vars]
PUBLIC_BUCKET_URL = "https://crossword.stubbs.me"  # Update after enabling public access

# R2 bucket binding
[[r2_buckets]]
binding = "CROSSWORD_BUCKET"
bucket_name = "nyt-crosswords"
preview_bucket_name = "nyt-crosswords"  # Use same bucket for dev

[[routes]]
pattern = "mini.stubbs.me"
custom_domain = true

[triggers]
crons = ["30 2,16 * * *"]  # Run daily


[assets]
directory = "public"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
