name = "nyt-mini-crossword-converter"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
PUBLIC_BUCKET_URL = "https://crossword.stubbs.me"  # Update after enabling public access

# R2 bucket binding
[[r2_buckets]]
binding = "CROSSWORD_BUCKET"
bucket_name = "nyt-crosswords"
preview_bucket_name = "nyt-crosswords"  # Use same bucket for dev

# Optional: Add a cron trigger to automatically fetch daily
[triggers]
crons = ["0 4 * * *"]  # Run at 4 AM UTC daily


[assets]
directory = "public"
